# Generated by Django 3.0.3 on 2020-02-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='desde',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experto',
            field=models.BooleanField(null=True),
        ),
    ]
