# Generated by Django 3.0.3 on 2020-02-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20200204_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hasta',
            field=models.TextField(null=True),
        ),
    ]
