# Generated by Django 3.0.3 on 2020-02-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_job_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desde',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='hasta',
            field=models.DateTimeField(null=True),
        ),
    ]
