# Generated by Django 3.0.3 on 2020-02-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_auto_20200204_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
    ]
